version: '3.4'

services:
  webserver:
    container_name: moat-webserver
    working_dir: /application
    image: nginx:alpine
    volumes:
      - .:/application
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8380:80
      - 8390:8080

  database:
    container_name: moat-database
    working_dir: /application
    image: mariadb:10.6
    environment:
      - MARIADB_USER=moatdbuser
      - MYSQL_DATABASE=music-collection
      - MARIADB_PASSWORD=123moat321
      - MARIADB_ROOT_PASSWORD=123root321
    volumes:
      - .:/application
      - ./configs/mariadb/my.cnf:/etc/mysql/conf.d/config-file.cnf
      - ./database:/var/lib/mysql
    ports:
      - 8306:3306

  php-fpm:
    container_name: moat-php-fpm
    working_dir: /application
    build: configs/php-fpm
    volumes:
      - .:/application
      - ./configs/php-fpm/99-overrides.ini:/etc/php/8.1/fpm/conf.d/99-overrides.ini
    ports:
      - 9020:9000